# -*- coding: utf-8 -*-
"""
/***************************************************************************
 S411_ICE_DATA
                                 A QGIS plugin
 Loads IHO S-411 Ice Data from BSH Server
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-02
        copyright            : (C) 2019 by Noiromo / Alexander Benke
        email                : a.benke@noiromo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load S411_ICE_DATA class from file S411_ICE_DATA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .s411_ice_data_loader import S411_ICE_DATA
    return S411_ICE_DATA(iface)
